config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'tasks_edit'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'
  patch '/tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    new_task = Task.new(task_params)
    new_task.save
    redirect_to task_path(new_task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    params[:task][:completed] == '1' ? @task.update(completed: true) : @task.update(completed: false)
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
  	@task.destroy
  	redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="style.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %> 
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.check_box :completed %>
  



  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div id="container"> 
  <h1 class="card-header">My tasks</h1>
    <form>
	  <% @tasks.each do |task| %>
	   	<% if task.completed %>
	   	<div class="card" style="width: 250px; padding: 20px 50px">
		  <input class="card-body" type="checkbox" checked ><%= link_to task.title, task_path(task) %><h6 id="bin_icon"><%= link_to "delete", task_path(task), method: :delete, data: { confirm: "Are you sure?" } %></h6><br>
		</div>
		  <% else %>
		<div class="card" style="width: 250px; padding: 20px 50px">
		  <input class="card-body" type="checkbox"><%= link_to task.title, task_path(task) %><h6 id="bin_icon"><%= link_to "delete", task_path(task), method: :delete, data: { confirm: "Are you sure?" } %></h6><br>
		</div>
		<% end %>
      <% end %>
	</form>
	<%= link_to 'Add a new task', tasks_new_path, class: "btn btn-primary" %>
  
</div>




 

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
	<div>
	  <%= f.label :title %>
	  <%= f.text_field :title %>
	</div>
	<div>
	  <%= f.label :details %>
	  <%= f.text_field :details %>
	</div>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%=  @task.title %></h1>
<p> <%= @task.details %></p>
  <%= button_to 'Edit this task', tasks_edit_path(@task), {method: :get} %>
<form>
	  <% if @task.completed %>
	    <input type="checkbox" checked><%= @task.title %> this task is complete <br>
	    <% else %>
	    <input type="checkbox"><%= @task.title %> this task is not complete <br>
	  <% end %>
</form>
<%= link_to 'Back to list of tasks', tasks_path, method: :get %>